name: Vermillion Throw Rug Runner

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: 
    inputs:
        debug:
          description: 'Enable Debugging'
          required: false
          default: 'true'
          type: choice
          options:
            - true
            - false
        disable_player_transactions:
          description: 'Disable Player Transactions'
          required: false
          default: 'true'
          type: choice
          options:
            - true
            - false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt
    - name: Run
      env:
        SWID: ${{ secrets.SWID }}
        ESPN_S2: ${{ secrets.ESPN_S2 }}
      run: |
        . .venv/bin/activate
        args=""
        if [ "${{ inputs.debug }}" == "true" ]; then
          args="-d"
        fi
        if [ "${{ inputs.disable_player_transactions }}" == "true" ]; then
          args="$args -p"
        fi
        python vtr_runner.py $args -s $SWID -e $ESPN_S2
        echo test >> data/matchup_settings.json
    - name: Commit matchup settings
      continue-on-error: true
      run: |
        git add data/matchup_settings.json
        git commit -m 'Automatic update of matchup settings.'
        git push
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: |
          output
          debug
          data/matchup_settings.json